# Generated by Django 3.1.7 on 2021-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210312_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['v_title'],
            },
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['title']},
        ),
    ]
