# Generated by Django 3.1.7 on 2021-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_word_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='v_title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
