# Generated by Django 3.1.7 on 2021-07-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20210413_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['title_show']},
        ),
        migrations.RenameField(
            model_name='word',
            old_name='title',
            new_name='title_algo',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='show_title',
            new_name='title_show',
        ),
    ]
