# Generated by Django 3.1.7 on 2021-08-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20210712_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='title_algo',
            new_name='titles_algo',
        ),
        migrations.RemoveField(
            model_name='word',
            name='voice',
        ),
        migrations.AddField(
            model_name='word',
            name='voices',
            field=models.ManyToManyField(to='apis.Voice'),
        ),
    ]
