# Generated by Django 3.1.7 on 2021-09-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20210906_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['title_for_show']},
        ),
        migrations.RenameField(
            model_name='word',
            old_name='category',
            new_name='category_names',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='title_show',
            new_name='title_for_show',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='titles_algo',
            new_name='titles_for_algo',
        ),
    ]
